### ISSUE TITLE
Sensor does not refresh 

### ISSUE THREAD

**Issue by msvinth** [Danielhiversen/home_assistant_airthings_cloud#10]
As far as I could from your code the sensor is supposed to refresh every 20 min.
This does not seem to work. 
For me the sensor only refreshes on Home Assistant restart.

Also tried to call homeassistant.update_entity but also not updating.

**Comment by Danielhiversen** [comment]
Any error in the logs?
Do you see your data here: https://dashboard.airthings.com/ ?

**Comment by msvinth** [comment]
Nothing the logs.
I see all data in the Airthings dashboard and the data is updated during the day.
And if I restart Home Assistant I do get new data as can be seen in screen shot where all the changes in values corresponds to me restarting HA.
![Screenshot 2020-10-30 at 14 24 29](https://user-images.githubusercontent.com/22496844/97710238-c74f4680-1abb-11eb-89ab-94b381c462a1.png)

**Comment by Danielhiversen** [comment]
Sorry, but without any from the log, it is nothing I can do.
I am afraid you would need to debug this yourself.

**Comment by msvinth** [comment]
Will you do a new release so this fix shows up in hacs? 🙂
