### ISSUE TITLE
Second Wave Mini

### ISSUE THREAD

**Issue by MeighenHouse** [Danielhiversen/home_assistant_airthings_cloud#17]
I've just recently added a second Wave Mini and it's not showing up in Home Assistant.  It's linked with the airthings hub, and showing up in the app.  It is not finished calibration yet.

**Comment by Danielhiversen** [comment]
Do you see it at https://dashboard.airthings.com/ ?

**Comment by MeighenHouse** [comment]
Just checked and it doesn't show up under Dashboard, but if I select devices it does there and I can select it and look at current and past values.

Perhaps it's related to the calibration time?  I'll let that complete and see if anything changes.

**Comment by MeighenHouse** [comment]
I did a little more digging on the dashboard and found that I can add the device to the dashboard. It doesn't add it automatically.

Now everything works fine. 

Sorry for the trouble.
