### ISSUE TITLE
Invalid E-mail incorrect error

### ISSUE THREAD

**Issue by Galapagon** [Danielhiversen/home_assistant_airthings_cloud#19]
When performing initial setup, leaving the email from the setup instructions unchanged produces an 

> Platform error sensor.airthings_cloud - Integration 'airthings_cloud' not found.

Error, instead of an invalid credentials error upon rebooting Home Assistant.

**Comment by Galapagon** [comment]
Issue is actually occurring because custom component must be added, Home Assistant reboot, then configured from YAML, I suggest adjusting the instructions accordingly.

**Comment by Danielhiversen** [comment]
That is standard procedure for any custom component, but a pull request is welcoome
