### ISSUE TITLE
Releases downloads entire github repository

### ISSUE THREAD

**Issue by Galapagon** [Danielhiversen/home_assistant_airthings_cloud#20]
https://github.com/Danielhiversen/home_assistant_airthings_cloud/releases/tag/0.1.3 downloads entire repository, I suggest adding an option so that only the airthings_cloud file is a download option, similar to how HACS is structured
EG: https://github.com/hacs/integration/releases/tag/1.9.0

**Comment by Danielhiversen** [comment]
Why?

**Comment by Galapagon** [comment]
The first time I tried adding it I put home_assistant_airthings_cloud-0.1.3 inside the custom components folder, not realizing that airthings_cloud was inside it, inside another custom components folder

**Comment by Danielhiversen** [comment]
I see your point, but do not think I will add that.
If you use hacs it will be handled automatically.
