### ISSUE TITLE
Version without binding to Home Assistant

### ISSUE THREAD

**Issue by rogerbl** [Danielhiversen/home_assistant_airthings_cloud#23]
Hi!
 Do you have a version of this without the binding to HA?
 I would like to login and collect this data from the Cloud and send it to a Mqtt broker where any automation system can fetch it.
Regards Roger

**Comment by Danielhiversen** [comment]
Currently not.
I am planning to split it into a separate python library.

**Comment by Danielhiversen** [comment]
Here https://github.com/Danielhiversen/pyAirthings
