### ISSUE TITLE
404 error, Airthings change something on their site?

### ISSUE THREAD

**Issue by MeighenHouse** [Danielhiversen/home_assistant_airthings_cloud#26]
Noticed the values weren't updating today and restarted Home Assistant. 

Now the log only shows this:

Logger: custom_components.airthings_cloud.sensor
Source: custom_components/airthings_cloud/sensor.py:247
Integration: airthings_cloud (documentation, issues) 
First occurred: 1:47:41 PM (1 occurrences) 
Last logged: 1:47:41 PM

Error connecting to Airthings, resp code: 404 Not Found

Been happening for a while now.  Website and app appear to be fine.

**Comment by iticory** [comment]
+1

It started doing the same thing for me today. :(

`This error originated from a custom integration.

Logger: custom_components.airthings_cloud.sensor
Source: custom_components/airthings_cloud/sensor.py:247
Integration: airthings_cloud (documentation, issues)
First occurred: 7:14:05 PM (1 occurrences)
Last logged: 7:14:05 PM

Error connecting to Airthings, resp code: 404 Not Found`

**Comment by gregology** [comment]
It looks like they changed the url from `https://web-api.airthin.gs/v1/dashboard` to `https://web-api.airthin.gs/v1/dashboards`. I'm testing that now

**Comment by gregology** [comment]
I have created a pull request to fix the new mapping. You can make the changes yourself in the existing installations

**Comment by Danielhiversen** [comment]
Fixed by https://github.com/Danielhiversen/home_assistant_airthings_cloud/pull/27
