### ISSUE TITLE
not found in HACS and no connection

### ISSUE THREAD

**Issue by legi1** [Danielhiversen/home_assistant_airthings_cloud#28]
Maybe I do somthing wrong.

Frist I cannot find airthings_cloud in HACS, only "Sensor.Airthings Wave" is found.
I've installed it coping your files in custom_components. Then restarted.
Now the logs tell me:
Logger: homeassistant.components.sensor
Source: /usr/local/lib/python3.8/asyncio/events.py:81
Integration: Sensor (documentation, issues)
First occurred: 10:26:10 (4 occurrences)
Last logged: 10:26:28

Setup of sensor platform airthings_cloud is taking over 10 seconds.
Setup of sensor platform solaredge is taking over 10 seconds.
Setup of sensor platform meteo-swiss is taking over 10 seconds.

and:
Logger: custom_components.airthings_cloud.sensor
Source: custom_components/airthings_cloud/sensor.py:62
Integration: airthings_cloud (documentation, issues)
First occurred: 10:26:20 (1 occurrences)
Last logged: 10:26:20

Failed to get data from Airthings

**Comment by Danielhiversen** [comment]
It is not an official HACS repo.

Can it be the same issue like this? https://github.com/Danielhiversen/home_assistant_airthings_cloud/issues/25#issuecomment-850746187

**Comment by legi1** [comment]
Thanks for the hint I'll try this.

**Comment by legi1** [comment]
The entities are now in HA but with errors:
Logger: homeassistant.components.sensor
Source: custom_components/airthings_cloud/sensor.py:97
Integration: Sensor (documentation, issues)
First occurred: 15:12:30 (2 occurrences)
Last logged: 15:12:30

Error adding entities for domain sensor with platform airthings_cloud
Error while setting up airthings_cloud platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 615, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 368, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 409, in _async_write_ha_state
    extra_state_attributes = self.device_state_attributes
  File "/config/custom_components/airthings_cloud/sensor.py", line 97, in device_state_attributes
    "timestamp": datetime.datetime.fromisoformat(
ValueError: Invalid isoformat string: ''

**Comment by legi1** [comment]
Problem solved "itself". After upgrading to 2021.7.1 and rebooting several times I discvered the sensors with values.
