### ISSUE TITLE
Support for PM

### ISSUE THREAD

**Issue by klein1jo** [Danielhiversen/home_assistant_airthings_cloud#29]
Using this with the new View Plus.  Works like a champ.  Missing particulate matter (PM) so requesting support for PM.

**Comment by Danielhiversen** [comment]
I do not have any of those devices, so it would requires someone else to do it.

**Comment by klein1jo** [comment]
Pull request with changes to support sensor types for particulate matter for View Plus.

https://github.com/Danielhiversen/home_assistant_airthings_cloud/pull/30
