### ISSUE TITLE
More Infos from ViewPlus

### ISSUE THREAD

**Issue by legi1** [Danielhiversen/home_assistant_airthings_cloud#35]
Hi I just installed my brand new ViewPlus. It is seen and I have the same entities as with the Plus. Now the ViewPuls has two more Sensors the PM1 and PM2.5, this ist not shown as an entity. Can you implement this?

**Comment by Danielhiversen** [comment]
It will be part of the Home Assistant 2021.10, then you do not need this integration anymore

**Comment by legi1** [comment]
Super Daniel, thanks for the info.

 

Von: Daniel Hjelseth Høyer ***@***.***>
Antworten an: Danielhiversen/home_assistant_airthings_cloud ***@***.***>
Datum: Dienstag, 28. September 2021 um 07:51
An: Danielhiversen/home_assistant_airthings_cloud ***@***.***>
Cc: Peter Bührer ***@***.***>, Author ***@***.***>
Betreff: Re: [Danielhiversen/home_assistant_airthings_cloud] More Infos from ViewPlus (#35)

 

It will be part of the Home Assistant 2021.10, then you do not need this integration anymore

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
